# Mole - Turkish (Türkçe) Localization
# Merkezi Türkçe çeviri dosyası.
# Bu dosyayı doğrudan düzenlemeyin — common.sh tarafından otomatik source edilir.

# Prevent multiple sourcing
if [[ -n "${MOLE_TR_LOADED:-}" ]]; then
    return 0
fi
readonly MOLE_TR_LOADED=1

# ============================================================================
# Dil Algılama / Language Detection
# ============================================================================
# macOS sistem dili AppleLanguages defaults anahtarından okunur.
# Aynı yöntem Mole'un Çince desteğinde de kullanılmaktadır.

_detect_turkish_system() {
    if [[ -n "${MOLE_IS_TURKISH_SYSTEM:-}" ]]; then
        return 0
    fi
    local primary_lang
    primary_lang=$(defaults read -g AppleLanguages 2>/dev/null \
        | sed -n 's/^[[:space:]]*"\([^"]*\)".*/\1/p' | head -1 || echo "")
    if [[ "$primary_lang" == tr || "$primary_lang" == tr-* ]]; then
        export MOLE_IS_TURKISH_SYSTEM="true"
    else
        export MOLE_IS_TURKISH_SYSTEM="false"
    fi
}
_detect_turkish_system

# ============================================================================
# Çeviri Değişkenleri / Translation Variables
# Sadece Türkçe sistem algılandığında atanır, aksi halde İngilizce kalır.
# ============================================================================

if [[ "${MOLE_IS_TURKISH_SYSTEM:-false}" == "true" ]]; then

# --------------------------------------------------------------------------
# Genel UI / General UI
# --------------------------------------------------------------------------
export TR_NOTHING_TO_CLEAN="Temizlenecek yok"
export TR_SCANNING="Taranıyor..."
export TR_SCANNING_ITEMS="Öğeler taranıyor..."
export TR_DRY_RUN_MODE="TEST MODU"
export TR_DRY_RUN_PREVIEW="Sadece önizleme, silme yok"
export TR_CANCELLED="İptal edildi"
export TR_UNKNOWN="Bilinmiyor"
export TR_NEVER="Hiç"

# --------------------------------------------------------------------------
# Zaman Etiketleri / Time Labels  (uninstall.sh, ui.sh)
# --------------------------------------------------------------------------
export TR_TIME_TODAY="Bugün"
export TR_TIME_YESTERDAY="Dün"
export TR_TIME_DAYS_AGO="gün önce"
export TR_TIME_WEEKS_AGO="hafta önce"
export TR_TIME_MONTHS_AGO="ay önce"
export TR_TIME_YEARS_AGO="yıl önce"
export TR_TIME_RECENT="Yakın zamanda"
export TR_TIME_THIS_YEAR="Bu yıl"
export TR_TIME_OLD="Eski"
export TR_TIME_ONE_WEEK_AGO="1 hafta önce"
export TR_TIME_ONE_MONTH_AGO="1 ay önce"
export TR_TIME_ONE_YEAR_AGO="1 yıl önce"

# --------------------------------------------------------------------------
# Ana Menü / Main Menu  (mole)
# --------------------------------------------------------------------------
export TR_MENU_CLEAN="Temizle      "
export TR_MENU_UNINSTALL="Kaldır       "
export TR_MENU_OPTIMIZE="Optimize     "
export TR_MENU_ANALYZE="Analiz       "
export TR_MENU_STATUS="Durum        "
export TR_MENU_CLEAN_DESC="Disk alanı boşalt"
export TR_MENU_UNINSTALL_DESC="Uygulamaları tamamen kaldır"
export TR_MENU_OPTIMIZE_DESC="Sistemi kontrol et"
export TR_MENU_ANALYZE_DESC="Disk kullanımını gör"
export TR_MENU_STATUS_DESC="Sistem sağlığını izle"
export TR_MENU_HINT="↑↓  |  Enter  |  M Daha  |  V Sürüm"

# --------------------------------------------------------------------------
# Temizleme / Clean  (bin/clean.sh)
# --------------------------------------------------------------------------
export TR_CLEAN_YOUR_MAC="Mac'inizi Temizleyin"
export TR_CLEAN_EXTERNAL="Harici Diski Temizle"
export TR_CLEAN_COMPLETE="Temizleme Tamamlandı"

# --------------------------------------------------------------------------
# Optimize  (bin/optimize.sh, lib/optimize/tasks.sh)
# --------------------------------------------------------------------------
export TR_OPT_TITLE="Optimize ve Kontrol"
export TR_OPT_COLLECTING_INFO="Sistem bilgisi toplanıyor..."
export TR_OPT_COMPLETE="Optimizasyon ve Kontrol Tamamlandı"
export TR_OPT_DRY_COMPLETE="Test Çalıştırması Tamamlandı"
export TR_OPT_RUN_WITHOUT="uygulamak için --dry-run olmadan çalıştırın"
export TR_OPT_SYSTEM_FULL="Sistem tam optimize edildi"
export TR_OPT_CACHE_CLEANED="önbellek temizlendi"
export TR_OPT_DB_OPTIMIZED="veritabanı optimize edildi"
export TR_OPT_CONFIG_REPAIRED="yapılandırma onarıldı"
export TR_OPT_DNS_FLUSHED="DNS önbelleği temizlendi"
export TR_OPT_DNS_REFRESHED="DNS önbelleği yenilendi"
export TR_OPT_DNS_RESTARTED="mDNSResponder yeniden başlatıldı"
export TR_OPT_SPOTLIGHT_OK="Spotlight dizini doğrulandı"
export TR_OPT_SPOTLIGHT_OFF="Spotlight dizini kapalı"
export TR_OPT_QL_REFRESHED="QuickLook küçük resimleri yenilendi"
export TR_OPT_ICON_REBUILT="Simge servisi önbelleği yeniden oluşturuldu"
export TR_OPT_SAVED_STATE="Uygulama kaydedilmiş durumları optimize edildi"
export TR_OPT_CHECKING_PREFS="Tercihler kontrol ediliyor..."
export TR_OPT_PREFS_OK="Tüm tercih dosyaları geçerli"
export TR_OPT_PREFS_REPAIR_FMT="%d bozuk tercih dosyası onarıldı"
export TR_OPT_DB_ALREADY_OK="Tüm veritabanları zaten optimize"
export TR_OPT_DB_OPTIMIZED_N="veritabanı optimize edildi (Mail, Safari, Mesajlar)"
export TR_OPT_DB_ALREADY_OPTIMAL_FMT="%s veritabanı zaten optimal"
export TR_OPT_DB_TIMED_OUT_FMT="%s veritabanında zaman aşımı"
export TR_OPT_DB_FAILED_FMT="%s veritabanında başarısız"
export TR_OPT_FONT_STILL_RUNNING="hâlâ çalışıyor"
export TR_OPT_OPTIMIZING_DBS="Veritabanları optimize ediliyor..."
export TR_OPT_LS_REPAIRING="LaunchServices onarılıyor..."
export TR_OPT_LS_REPAIRED="LaunchServices onarıldı"
export TR_OPT_FA_REFRESHED="Dosya ilişkileri yenilendi"
export TR_OPT_MEM_OPTIMAL="Bellek baskısı zaten optimal"
export TR_OPT_MEM_RELEASED="Atıl bellek serbest bırakıldı"
export TR_OPT_MEM_IMPROVED="Sistem yanıt hızı iyileştirildi"
export TR_OPT_NET_OPTIMAL="Ağ yığını zaten optimal"
export TR_OPT_ROUTE_REFRESHED="Ağ yönlendirme tablosu yenilendi"
export TR_OPT_ARP_CLEARED="ARP önbelleği temizlendi"
export TR_OPT_QUARANTINE_OK="Karantina veritabanı zaten temiz"
export TR_OPT_QUARANTINE_CLEARED="Karantina geçmişi temizlendi"
export TR_OPT_FONT_CACHE="Font önbelleği temizlendi"
export TR_OPT_FONT_REBUILD="Sistem font veritabanını otomatik yeniden oluşturacak"
export TR_OPT_PERM_OPTIMAL="Kullanıcı dizin izinleri optimal"
export TR_OPT_PERM_REPAIRED="Kullanıcı dizin izinleri onarıldı"
export TR_OPT_PERM_FIXED="Dosya erişim sorunları çözüldü"
export TR_OPT_BT_OPTIMAL="Bluetooth zaten optimal"
export TR_OPT_BT_RESTARTED="Bluetooth modülü yeniden başlatıldı"
export TR_OPT_BT_RESOLVED="Bağlantı sorunları çözüldü"
export TR_OPT_CHECKING_BT="Bluetooth kontrol ediliyor..."
export TR_OPT_REPAIRING_DISK="Disk izinleri onarılıyor..."

# --------------------------------------------------------------------------
# Güvenlik / Security  (bin/optimize.sh güvenlik bölümü)
# --------------------------------------------------------------------------
export TR_SECURITY_TITLE="GÜVENLİK DÜZELTMELERİ"
export TR_SECURITY_APPLY_NOW="Şimdi uygula?"
export TR_SECURITY_CONFIRM_HINT="Enter onayla / Space iptal"
export TR_SECURITY_SKIPPED="Güvenlik düzeltmeleri atlandı"
export TR_SECURITY_SUDO_DENIED="Yönetici erişimi reddedildi"
export TR_SECURITY_FW_ENABLED="Güvenlik duvarı etkinleştirildi"
export TR_SECURITY_FW_FAIL="Güvenlik duvarı etkinleştirilemedi"
export TR_SECURITY_ENABLE_FW="macOS güvenlik duvarını etkinleştir"
export TR_SECURITY_ENABLE_TOUCHID="Sudo için Touch ID etkinleştir"
export TR_SECURITY_ADMIN_REQ="Güvenlik değişiklikleri yönetici ister"
export TR_SECURITY_UPDATED="Güvenlik ayarları güncellendi"

# --------------------------------------------------------------------------
# Sistem Kontrolleri / System Checks  (lib/check/all.sh)
# --------------------------------------------------------------------------
export TR_CHK_SYS_CONFIG="Sistem Yapılandırması"
export TR_CHK_SECURITY="Güvenlik Durumu"
export TR_CHK_UP_TO_DATE="Güncel"
export TR_CHK_LATEST="En son sürüm"
export TR_CHK_UPDATE_AVAIL="Güncelleme mevcut"
export TR_CHK_SYS_UP_TO_DATE="Sistem güncel"
export TR_CHK_NOT_INSTALLED="Kurulu değil"
export TR_CHK_TOUCH_ID_ON="Touch ID etkin"
export TR_CHK_TOUCH_ID_OFF="Sudo için yapılandırılmamış"
export TR_CHK_INTEL_READY="Intel uygulama dönüştürme hazır"
export TR_CHK_GIT_OK="Global kimlik yapılandırıldı"
export TR_CHK_GIT_OFF="Kullanıcı kimliği ayarlanmamış"
export TR_CHK_FV_ON="Disk şifrelemesi aktif"
export TR_CHK_FV_OFF="Disk şifrelemesi kapalı"
export TR_CHK_FW_ON="Ağ koruması etkin"
export TR_CHK_FW_OFF="Ağ koruması kapalı"
export TR_CHK_GK_ON="Uygulama güvenliği aktif"
export TR_CHK_GK_OFF="Uygulama güvenliği kapalı"
export TR_CHK_SIP_ON="Sistem bütünlüğü korunuyor"
export TR_CHK_SIP_OFF="Sistem koruması kapalı"
export TR_CHK_DISK_CRIT="Kritik"
export TR_CHK_DISK_LOW="Düşük"
export TR_CHK_MEM_CRIT="Kritik"
export TR_CHK_MEM_HIGH="Yüksek"
export TR_CHK_DISK_HEALTH_VERF="SMART Doğrulandı"
export TR_CHK_DISK_HEALTH_FAIL="SMART Başarısız — hemen yedek alın"
export TR_CHK_LOGIN_ITEMS="Giriş Öğeleri"
export TR_CHK_LOGIN_NONE="Yok"
export TR_CHK_CHECKING_ITEMS="Giriş öğeleri kontrol ediliyor..."
export TR_CHK_SCANNING_CACHE="Önbellek taranıyor..."
export TR_CHK_FW_ACTIVE="etkin"
export TR_CHK_CHECKING_UPDATES="Sistem güncellemeleri kontrol ediliyor..."
export TR_CHK_HB_NOT_INSTALLED="Kurulu değil"
export TR_CHK_CHECKING_BREW="Homebrew güncellemeleri kontrol ediliyor..."
export TR_CHK_TIMED_OUT="Kontrol zaman aşımına uğradı"
export TR_CHK_FAILED="Kontrol başarısız oldu"
export TR_CHK_HB_FORMULA="formül"
export TR_CHK_HB_CASK="cask"
export TR_CHK_CHECKING_MOLE_VER="Mole sürümü kontrol ediliyor..."
export TR_CHK_RUNNING_VERSION="çalışıyor"
export TR_CHK_SYSTEM_UPDATES="Sistem Güncellemeleri"
export TR_CHK_DISK_FREE="boş"
export TR_CHK_MEM_UNKNOWN="Belirlenemiyor"
export TR_CHK_MEM_USED="kullanılıyor"
export TR_CHK_LOGIN_APPS="uygulama"
export TR_CHK_CACHE_CLEANABLE_LBL="temizlenebilir"
export TR_CHK_SWAP_HIGH_LBL="Yüksek"
export TR_CHK_LA_NONE_ORPHANED="Yetim öğe yok"
export TR_CHK_LA_ORPHAN="yetim"
export TR_CHK_LA_ORPHANS="yetim"
export TR_CHK_SYSTEM_HEALTH="Sistem Sağlığı"
export TR_CHK_HOMEBREW_LABEL="Homebrew"
export TR_CHK_MACOS_LABEL="macOS"
export TR_CHK_MOLE_LABEL="Mole"
export TR_CHK_DISK_SPACE="Disk Alanı"
export TR_CHK_MEMORY="Bellek"
export TR_CHK_CACHE_SIZE="Önb. Boyutu"
export TR_CHK_SWAP_USAGE="Takas Kullanımı"
export TR_CHK_DISK_HEALTH="Disk Sağlığı"
export TR_CHK_LAUNCH_AGENTS="Başlatma Aracıları"

# --------------------------------------------------------------------------
# Güncellemeler / Updates
# --------------------------------------------------------------------------
export TR_UPD_AVAIL="mevcut"
export TR_UPD_CONFIRM="Enter onayla / Space atla"
export TR_UPD_UPDATING_HB="Homebrew güncelleniyor..."
export TR_UPD_UPGRADING_MOLE="Mole yükseltiliyor..."
export TR_UPD_ALREADY_LATEST="Zaten son sürümdesiniz"
export TR_UPD_UPDATED="Son sürüme güncellendi"

# --------------------------------------------------------------------------
# Kaldırma / Uninstall  (bin/uninstall.sh, lib/uninstall/batch.sh)
# --------------------------------------------------------------------------
export TR_UNINSTALL_SELECT="Kaldırılacak Uygulamaları Seçin"
export TR_UNINSTALL_SCANNING="Uygulamalar taranıyor..."
export TR_UNINSTALL_BUILDING="Kaldırma dizini oluşturuluyor..."
export TR_UNINSTALL_MERGING="Önbellek verileri birleştiriliyor..."
export TR_UNINSTALL_SORTING="Uygulama listesi sıralanıyor..."
export TR_UNINSTALL_FINALIZING="Liste sonuçlandırılıyor..."
export TR_UNINSTALL_METADATA="Meta veriler toplanıyor..."
export TR_UNINSTALL_CACHE="Önbellek güncelleniyor..."
export TR_UNINSTALL_NO_APPS="Kaldırılacak uygulama bulunamadı"
export TR_UNINSTALL_REMOVED="kaldırıldı"

# --------------------------------------------------------------------------
# Temizlik Bölümleri / Clean Sections  (lib/clean/*.sh)
# --------------------------------------------------------------------------
export TR_SEC_APP_CACHES="Uygulama önbellekleri"
export TR_SEC_SYSTEM="Sistem Dosyaları"
export TR_SEC_USER_ESSENTIALS="Kullanıcı dosyaları"
export TR_SEC_BROWSERS="Tarayıcılar"
export TR_SEC_CLOUD_OFFICE="Bulut ve Ofis"
export TR_SEC_DEV_TOOLS="Geliştirici araçları"
export TR_SEC_APPLICATIONS="Uygulamalar"
export TR_SEC_VIRTUALIZATION="Sanallaştırma"
export TR_SEC_APP_SUPPORT="Uygulama Desteği"
export TR_SEC_APP_LEFTOVERS="Uygulama kalıntıları"
export TR_SEC_DEVICE_BACKUPS="Cihaz yedekleri ve yazılımı"
export TR_SEC_TIME_MACHINE="Time Machine"
export TR_SEC_LARGE_FILES="Büyük dosyalar"
export TR_SEC_SYSTEM_DATA="Sistem Verisi ipuçları"
export TR_SEC_PROJECT_ART="Proje kalıntıları"
export TR_SEC_EXTERNAL_VOLUME="Harici birim"

# --------------------------------------------------------------------------
# Purge  (bin/purge.sh)
# --------------------------------------------------------------------------
export TR_PURGE_TITLE="Proje Dosyalarını Temizle"
export TR_PURGE_SCANNING="Taranıyor "
export TR_PURGE_COMPLETE="Temizleme tamamlandı"
export TR_PURGE_DRY_COMPLETE="Test tamamlandı - değişiklik yapılmadı"
export TR_PURGE_NO_ARTIFACTS="Temizlenecek eski proje kalıntısı yok."
export TR_PURGE_WARN_SAVE="Yapılandırma kaydedilemedi:"
export TR_PURGE_WARN_USE_DISC="bu oturum için otomatik dizinler kullanılacak"
export TR_PURGE_FIRST_RUN="İlk çalıştırma: proje dizinleri aranıyor..."
export TR_PURGE_FOUND="Bulunan:"
export TR_PURGE_SAVED="proje dizini yapılandırmaya eklendi"
export TR_PURGE_ITEMS="Öğeler"
export TR_PURGE_FREE="Boş"
export TR_PURGE_FREE_SPACE="Boş alan"
export TR_PURGE_UNKNOWN_OPT_MSG="Bilinmeyen seçenek:"
export TR_PURGE_DRY_RUN_DETAIL="Proje kalıntıları kaldırılmayacak"
export TR_PURGE_SCANNING_DOTS="Taranıyor..."
export TR_PURGE_HELP_TITLE="Mole Purge"
export TR_PURGE_HELP_DESC="Eski proje derleme kalıntılarını temizle"
export TR_PURGE_HELP_USAGE="Kullanım: mo purge [seçenekler]"
export TR_PURGE_HELP_OPTIONS="Seçenekler:"
export TR_PURGE_HELP_PATHS="--paths         Tarama dizinlerini düzenle"
export TR_PURGE_HELP_DRYRUN="--dry-run       Değişiklik yapmadan önizle"
export TR_PURGE_HELP_DEBUG="--debug         Hata ayıklama günlüğünü etkinleştir"
export TR_PURGE_HELP_HELP="--help          Bu yardım mesajını göster"
export TR_PURGE_DEFAULT_PATHS="Varsayılan Dizinler:"
export TR_PURGE_HELP_HINT="Kullanım bilgisi için 'mo purge --help' yazın"
export TR_PURGE_ARTIFACT="kalıntı"
export TR_PURGE_ARTIFACTS="kalıntı"
export TR_PURGE_UNKNOWN_SIZE="bilinmeyen boyut"
export TR_PURGE_UNKNOWN_SIZES="bilinmeyen boyutlar"
export TR_PURGE_SELECTED_PATHS="Seçilen yollar:"
export TR_PURGE_NO_SELECTED="Seçim yok"
export TR_PURGE_NONE_FOUND="Temizlenecek kalıntı yok"

# --------------------------------------------------------------------------
# Yükleyici / Installer  (bin/installer.sh)
# --------------------------------------------------------------------------
export TR_INST_SCANNING="Yükleyiciler taranıyor..."
export TR_INST_SIZES="Boyutlar hesaplanıyor..."
export TR_INST_GREAT="Harika! Temizlenecek yükleyici yok"
export TR_INST_COMPLETE="Yükleyiciler temizlendi"
export TR_INST_DRY_COMPLETE="Test çalıştırması tamamlandı"
export TR_INST_MAC_CLEANER="Mac'iniz artık daha temiz!"
export TR_INST_REMOVED_N="yükleyici kaldırıldı"
export TR_INST_WOULD_REMOVE="kaldırılacak"
export TR_INST_WOULD_FREE="Kazanılacak alan"
export TR_INST_FILES_TO_RM="Kaldırılacak dosyalar:"
export TR_INST_DELETE_VERB="Sil"
export TR_INST_DELETE_CONFIRM="yükleyici"
export TR_INST_NO_REMOVED="Yükleyici kaldırılmadı"
export TR_INST_SELECT_TITLE="Kaldırılacak Yükleyicileri Seçin"
export TR_INST_SELECTED="seçili"
export TR_INST_CONTROLS="Space Seç  |  Enter Onayla  |  A Tümü  |  I Ters  |  Q Çıkış"
export TR_INST_REMOVING_MSG="Yükleyiciler kaldırılıyor..."
export TR_INST_UNKNOWN_OPT_MSG="Bilinmeyen seçenek:"
export TR_INST_DRY_NO_FILES="Yükleyici dosyası kaldırılmayacak"

# --------------------------------------------------------------------------
# Touch ID  (bin/touchid.sh)
# --------------------------------------------------------------------------

export TR_BIN_TID_ENABLED="Touch ID sudo için etkinleştirildi"
export TR_BIN_TID_NOT_CONFIGURED="Touch ID sudo için yapılandırılmamış"
export TR_BIN_TID_ALREADY_ENABLED="Touch ID zaten etkin, değişiklik gerekmiyor"
export TR_BIN_TID_DRY_ENABLE="[TEST MODU] Touch ID sudo için etkinleştirilecek"
export TR_BIN_TARGET_FILES="Hedef dosyalar:"
export TR_BIN_TID_MAY_NOT_SUPPORT="Bu Mac Touch ID desteklemiyor olabilir"
export TR_BIN_CONTINUE_ANYWAY="Yine de devam edilsin mi? [e/H]"
export TR_BIN_CANCELLED="İptal edildi"
export TR_BIN_TID_CLEANUP_LEGACY="Eski yapılandırma temizlendi"
export TR_BIN_TID_ALREADY="Touch ID zaten etkin"
export TR_BIN_TID_MIGRATED="Touch ID sudo_local dosyasına taşındı"
export TR_BIN_TID_ENABLED_LOCAL="Touch ID sudo_local üzerinden etkinleştirildi, test edin: sudo ls"
export TR_BIN_TID_ERR_LOCAL="sudo_local dosyasına yazılamadı"
export TR_BIN_ERR_BACKUP="Yedek oluşturulamadı"
export TR_BIN_ERR_MOD_CONF="Yapılandırma değiştirilemedi"
export TR_BIN_TID_ENABLED_TRY="Touch ID etkinleştirildi, test edin: sudo ls"
export TR_BIN_ERR_ENABLE="Touch ID etkinleştirilemedi"
export TR_BIN_TID_NOT_ENABLED="Touch ID şu anda etkin değil"
export TR_BIN_TID_DRY_DISABLE="[TEST MODU] Touch ID sudo için devre dışı bırakılacak"
export TR_BIN_TID_DISABLED="Touch ID devre dışı bırakıldı"
export TR_BIN_ERR_DISABLE="Touch ID devre dışı bırakılamadı"
export TR_BIN_ERR_CONF_NOT_FOUND="Devre dışı bırakılacak Touch ID yapılandırması bulunamadı"
export TR_BIN_PRESS_ENTER_DIS="Devre dışı bırakmak için Enter'a, çıkmak için Q'ya basın:"
export TR_BIN_INVALID_KEY="Geçersiz tuş"
export TR_BIN_PRESS_ENTER_EN="Etkinleştirmek için Enter'a, çıkmak için Q'ya basın:"
export TR_BIN_ONLY_ONE_CMD="Her çalıştırmada yalnızca bir touchid komutu desteklenir"
export TR_BIN_UNKNOWN_CMD="Bilinmeyen komut:"
export TR_BIN_DRY_RUN_MODE="TEST MODU, Kimlik doğrulama dosyaları değiştirilmeyecek"

# --------------------------------------------------------------------------
# Menü Kontrol Tuşları / Menu Control Keys  (lib/ui/*)
# --------------------------------------------------------------------------
export TR_MENU_SPACE_SELECT="Space Seç"
export TR_MENU_ENTER="Enter Onayla"
export TR_MENU_Q_EXIT="Q Çıkış"
export TR_MENU_A_ALL="A Tümü"
export TR_MENU_I_INVERT="I Tersine Çevir"
export TR_MENU_SORT_DATE="Tarih"
export TR_MENU_SORT_NAME="İsim"
export TR_MENU_SORT_SIZE="Boyut"
export TR_MENU_SEARCH="/ Ara"
export TR_MENU_NO_ITEMS="Öğe bulunamadı"
export TR_MENU_SELECTED="seçili"
export TR_MENU_BACKSPACE="Geri Al"
export TR_MENU_CTRL_CLEAR="Ctrl+U Temizle"
export TR_MENU_ESC_CLEAR="ESC Temizle"
export TR_MENU_SEARCH_LABEL="Ara: "
export TR_MENU_TYPE_TO_SEARCH="aramak için yazın"
export TR_MENU_RECENT="Son"
export TR_MENU_SELECT_CATS="Temizlenecek Kategorileri Seçin"
export TR_MENU_FULL_PATH="Tam yol:"
export TR_MENU_T_TOUCHID="T TouchID"
export TR_MENU_U_UPDATE="U Güncelle"
export TR_MENU_ERR_NO_ITEMS="Öğe verilmedi"

# --------------------------------------------------------------------------
# Yardım / Help  (lib/core/help.sh)
# --------------------------------------------------------------------------
export TR_HELP_USAGE="Kullanım"
export TR_HELP_MAIN_MENU_DESC="Etkileşimli menü"
export TR_HELP_OPTIONS="Seçenekler:"
export TR_HELP_COMMANDS="Komutlar:"
export TR_HELP_EXAMPLES="Örnekler:"
export TR_HELP_DEBUG="Ayrıntılı işlem günlükleri göster"
export TR_HELP_SHOW_HELP="Bu yardım mesajını göster"
export TR_HELP_PATH_ARG="YOL"

# clean help
export TR_HELP_CLEAN_USAGE="Kullanım: mo clean [SEÇENEKLER]"
export TR_HELP_CLEAN_DESC="Önbellekler, günlükler, geçici dosyalar ve kaldırılmış uygulamaların artıklarını silerek disk alanı boşaltır."
export TR_HELP_CLEAN_DRY="Değişiklik yapmadan temizliği önizle"
export TR_HELP_CLEAN_EXTERNAL="Bağlı harici disk için OS meta verilerini temizle"
export TR_HELP_CLEAN_WHITELIST="Korunan yolları yönet"

# installer help
export TR_HELP_INST_USAGE="Kullanım: mo installer [SEÇENEKLER]"
export TR_HELP_INST_DESC="Yükleyici dosyalarını (.dmg, .pkg, .iso, .xip, .zip) bul ve kaldır."
export TR_HELP_INST_DRY="Değişiklik yapmadan yükleyici temizliğini önizle"

# optimize help
export TR_HELP_OPT_USAGE="Kullanım: mo optimize [SEÇENEKLER]"
export TR_HELP_OPT_DESC="Sistem sağlığını kontrol et ve bakımını yap, optimizasyonları uygula."
export TR_HELP_OPT_DRY="Değişiklik yapmadan optimizasyonu önizle"
export TR_HELP_OPT_WHITELIST="Korunan öğeleri yönet"

# touchid help
export TR_HELP_TID_USAGE="Kullanım: mo touchid [KOMUT]"
export TR_HELP_TID_DESC="Sudo kimlik doğrulaması için Touch ID'yi yapılandır."
export TR_HELP_TID_ENABLE="Sudo için Touch ID'yi etkinleştir"
export TR_HELP_TID_DISABLE="Sudo için Touch ID'yi devre dışı bırak"
export TR_HELP_TID_STATUS="Mevcut Touch ID durumunu göster"
export TR_HELP_TID_DRY="Sudo yapılandırmasını değiştirmeden Touch ID değişikliklerini önizle"
export TR_HELP_TID_FOOTER="Komut belirtilmezse etkileşimli menü gösterilir."

# uninstall help
export TR_HELP_UNI_USAGE="Kullanım: mo uninstall [SEÇENEKLER] [UYGULAMA_ADI ...]"
export TR_HELP_UNI_DESC_1="Uygulamaları ve artık dosyalarını etkileşimli olarak kaldır."
export TR_HELP_UNI_DESC_2="İsteğe bağlı olarak doğrudan kaldırılacak uygulama adları belirtilebilir."
export TR_HELP_UNI_DESC_3="Zaten kaldırılmış uygulamaların artıkları için: mo clean"
export TR_HELP_UNI_EX_1="Etkileşimli uygulama seçiciyi aç"
export TR_HELP_UNI_EX_2="Slack'i kaldır"
export TR_HELP_UNI_EX_3="Slack ve Zoom'u kaldır"
export TR_HELP_UNI_EX_4="Slack kaldırımını önizle"
export TR_HELP_UNI_DRY="Değişiklik yapmadan uygulama kaldırımını önizle"
export TR_HELP_UNI_WHITELIST="Kaldırma için desteklenmiyor (clean/optimize kullanın)"

# --------------------------------------------------------------------------
# Komut Açıklamaları / Command Descriptions  (lib/core/commands.sh)
# --------------------------------------------------------------------------
export TR_CMD_CLEAN="Disk alanı boşalt"
export TR_CMD_UNINSTALL="Uygulamaları tamamen kaldır"
export TR_CMD_OPTIMIZE="Sistemi kontrol et ve bakımını yap"
export TR_CMD_ANALYZE="Disk kullanımını keşfet"
export TR_CMD_STATUS="Sistem sağlığını izle"
export TR_CMD_PURGE="Eski proje dosyalarını kaldır"
export TR_CMD_INSTALLER="Yükleyici dosyalarını bul ve kaldır"
export TR_CMD_TOUCHID="Sudo için Touch ID yapılandır"
export TR_CMD_COMPLETION="Kabuk sekme tamamlama kur"
export TR_CMD_UPDATE="Son sürüme güncelle"
export TR_CMD_REMOVE="Mole'u sistemden kaldır"
export TR_CMD_HELP="Yardımı göster"
export TR_CMD_VERSION="Sürümü göster"

# --------------------------------------------------------------------------
# version / update / remove mesajları  (mole ana script)
# --------------------------------------------------------------------------
export TR_UPDATE_LATEST="Zaten son sürümdesiniz"

export TR_BIN_NEW_NIGHTLY="Yeni nightly sürümü %s mevcut, çalıştırmak için:"
export TR_BIN_UPDATE_MSG="%s Güncellemesi mevcut, çalıştırmak için:"
export TR_BIN_MOLE_DOWNLOADING="Son sürüm indiriliyor..."
export TR_BIN_MOLE_INSTALLING="Güncelleme yükleniyor..."
export TR_BIN_MOLE_LATEST_LBL="son sürüme"
export TR_BIN_MOLE_DOWN_NIGHTLY="Nightly sürüm indiriliyor..."
export TR_BIN_MOLE_INSTALL_NIGHTLY="Nightly güncellemesi yükleniyor..."
export TR_BIN_MOLE_NIGHTLY_BLD="nightly build (main) sürümüne"
export TR_BIN_MOLE_TAGLINE="Mac'ini derinlemesine temizle ve optimize et."

export TR_REMOVE_DETECTING="Mole kurulumları aranıyor..."
export TR_REMOVE_NO_INSTALL="Hiçbir mole kurulumu bulunamadı"
export TR_REMOVE_TITLE="Mole'ü Kaldır"
export TR_REMOVE_WOULD_DEL="şunları silecekti:"
export TR_REMOVE_WOULD_RUN="Çalıştırılacaktı:"
export TR_REMOVE_WOULD_DEL_ITEM="Silinecekti:"
export TR_REMOVE_WILL_DEL="şunlar silinecek:"
export TR_REMOVE_VIA_BREW="Homebrew ile Mole"
export TR_REMOVE_CONFIRM="Onaylamak için Enter, iptal için ESC tuşuna basın: "
export TR_REMOVE_BREW_FAIL="Homebrew bulunamadı."
export TR_REMOVE_ATTEMPT_BREW="Homebrew ile Mole'ü kaldırma deneniyor..."
export TR_REMOVE_BREW_UN_FAIL="Homebrew kaldırma başarısız:"
export TR_REMOVE_MANUAL_STEP="Manuel adım:"
export TR_REMOVE_BREW_UN_SUCC="Mole, Homebrew ile kaldırıldı."
export TR_REMOVE_DONE_WARN="Mole kaldırıldı, bazı hatalar oluştu; kullandığınız için teşekkürler!"
export TR_REMOVE_DONE_SUCCESS="Mole sorunsuz kaldırıldı; kullandığınız için teşekkürler!"

export TR_DRY_NO_FILES="hiçbir dosya silinmeyecek"
export TR_UNKNOWN_COMMAND="Bilinmeyen komut"
export TR_MOLE_UPDATE_HINT="Desteklenen seçenekler için 'mole update [--force] [--nightly]' kullanın."
export TR_MOLE_REMOVE_HINT="Desteklenen seçenekler için 'mole remove [--dry-run]' kullanın."
export TR_MOLE_HELP_HINT="Kullanım bilgisi için 'mole --help' yazın."
export TR_TOUCHID_DISABLED="Touch ID başarıyla devre dışı bırakıldı."
export TR_TOUCHID_DISABLE_FAILED="Touch ID devre dışı bırakılamadı."

# mole — show_help / show_version / güncelleme (mole)
export TR_MOLE_HELP_CMDS="KOMUTLAR"
export TR_MOLE_HELP_OPTS="SEÇENEKLER"
export TR_MOLE_HELP_MAIN_MENU="Ana menü"
export TR_MOLE_HELP_PREVIEW_CLEAN="Temizliği önizle"
export TR_MOLE_HELP_MANAGE_WL="Korumalı önbellekleri yönet"
export TR_MOLE_HELP_PREVIEW_OPT="Optimizasyonu önizle"
export TR_MOLE_HELP_MANAGE_PROT="Korumalı öğeleri yönet"
export TR_MOLE_HELP_PREVIEW_UN="Uygulama kaldırmayı önizle"
export TR_MOLE_HELP_PREVIEW_PURGE="Proje temizliğini önizle"
export TR_MOLE_HELP_PREVIEW_INST="Yükleyici temizliğini önizle"
export TR_MOLE_HELP_PREVIEW_TID="Touch ID kurulumunu önizle"
export TR_MOLE_HELP_PREVIEW_COMP="Kabuk tamamlama düzenini önizle"
export TR_MOLE_HELP_PURGE_PATHS="Tarama dizinlerini yapılandır"
export TR_MOLE_HELP_ANALYZE_EXT="Yalnızca harici diskleri analiz et"
export TR_MOLE_HELP_UPDATE_FORCE="Kararlı sürümü zorla yeniden kur"
export TR_MOLE_HELP_UPDATE_NIGHTLY="Ana daldaki nightly sürümü kur"
export TR_MOLE_HELP_REMOVE_DRY="Mole kaldırmayı önizle"
export TR_MOLE_HELP_DEBUG="Ayrıntılı günlükleri göster"
export TR_MOLE_VER_TITLE="Mole sürümü %s"
export TR_MOLE_VER_CHANNEL_NIGHTLY="Kanal: Nightly (%s)"
export TR_MOLE_VER_CHANNEL_NIGHTLY_SHORT="Kanal: Nightly"
export TR_MOLE_VER_MACOS="macOS: %s"
export TR_MOLE_VER_ARCH="Mimari: %s"
export TR_MOLE_VER_KERNEL="Çekirdek: %s"
export TR_MOLE_VER_SIP="SIP: %s"
export TR_MOLE_VER_DISK_FREE="Boş disk: %s"
export TR_MOLE_VER_INSTALL="Kurulum: %s"
export TR_MOLE_VER_SHELL="Kabuk: %s"
export TR_MOLE_VER_UNKNOWN="Bilinmiyor"
export TR_MOLE_VER_MANUAL="Elle"
export TR_MOLE_VER_HB="Homebrew"
export TR_MOLE_ERR_NIGHTLY_HB="Nightly yalnızca betik kurulumda"
export TR_MOLE_MSG_HB_STABLE="Homebrew kararlı sürüm kullanır."
export TR_MOLE_MSG_HB_SCRIPT="Nightly için betikle yeniden kurun:"
export TR_MOLE_ERR_UPDATE_CHECK="Güncelleme kontrol edilemedi."
export TR_MOLE_MSG_GITHUB="GitHub erişimini denetleyin."
export TR_MOLE_MSG_TRY_UPDATE="Tekrar deneyin:"
export TR_MOLE_ERR_UPDATE_FAIL="Güncelleme başarısız"
export TR_MOLE_ERR_CURL="curl hata kodu: %s"
export TR_MOLE_ERR_NET_DNS="Sunucu çözülemedi. DNS veya ağı denetleyin."
export TR_MOLE_ERR_NET_CONN="Bağlantı kurulamadı. Ağ veya vekil."
export TR_MOLE_ERR_HTTP_404="HTTP 404. Yükleyici taşınmış olabilir."
export TR_MOLE_ERR_NET_TIMEOUT="Zaman aşımı. Güvenlik duvarını denetleyin."
export TR_MOLE_ERR_NET_GENERIC="Ağı denetleyip tekrar deneyin."
export TR_MOLE_MSG_URL="Adres:"
export TR_MOLE_ERR_WGET="wget ile indirme başarısız"
export TR_MOLE_ERR_CURL_WGET="curl veya wget gerekli"
export TR_MOLE_MSG_INSTALL_CURL="curl kurun:"
export TR_MOLE_MSG_UPDATED_TO="Güncellendi:"
export TR_MOLE_ERR_UPDATE_ABORT="Güncelleme iptal, yönetici reddi"
export TR_MOLE_PROMPT_UPDATE_SUDO="Mole güncellemesi yönetici ister"

# --------------------------------------------------------------------------
# install.sh (betik kurulum)
# --------------------------------------------------------------------------
export TR_INSTALL_FETCH_SRC="Mole kaynağı indiriliyor, %s..."
export TR_INSTALL_CLONE_SRC="Mole kaynağı klonlanıyor..."
export TR_INSTALL_ERR_TAG="Sürüm %s alınamadı. Etiket var mı?"
export TR_INSTALL_ERR_FETCH_SRC="Kaynak alınamadı. curl veya git gerekli."
export TR_INSTALL_ERR_MACOS_ONLY="Bu araç yalnızca macOS içindir"
export TR_INSTALL_WARN_HB_STALE="Eski Homebrew kurulumu temizleniyor..."
export TR_INSTALL_ERR_PARENT_DIR="Üst dizin yok: %s"
export TR_INSTALL_ERR_CONFIG_MK="Yapılandırma dizini oluşturulamadı: %s"
export TR_INSTALL_OK_BUILT="Kaynaktan derlendi: %s"
export TR_INSTALL_WARN_BUILD_FAIL="%s kaynaktan derlenemedi"
export TR_INSTALL_OK_INST_LOCAL="Yerel %s ikili kuruldu"
export TR_INSTALL_WARN_NO_VER="%s sürümü belirlenemedi, yerel derleme deneniyor"
export TR_INSTALL_OK_DOWNLOADED="%s ikili indirildi"
export TR_INSTALL_WARN_DL_FAIL="%s v%s indirilemedi, yerel derleme"
export TR_INSTALL_ERR_INST_BIN="%s ikili kurulamadı"
export TR_INSTALL_MSG_ADMIN_USR_LOCAL="/usr/local/bin için yönetici gerekli"
export TR_INSTALL_OK_MOLE_TO="mole şuraya kuruldu: %s"
export TR_INSTALL_ERR_MOLE_MISSING="mole çalıştırılabilir dosyası yok: %s"
export TR_INSTALL_OK_MO_ALIAS="mo takma adı zaten var"
export TR_INSTALL_OK_MO_INST="mo takma adı kuruldu"
export TR_INSTALL_OK_MOD_SYNC="Modüller güncel"
export TR_INSTALL_OK_MOD_INST="Modüller kuruldu"
export TR_INSTALL_OK_LIB_SYNC="Kitaplıklar güncel"
export TR_INSTALL_OK_LIB_INST="Kitaplıklar kuruldu"
export TR_INSTALL_WARN_VERIFY="Mole kuruldu ancak doğrulama sorunlu olabilir"
export TR_INSTALL_ERR_VERIFY="Kurulum doğrulaması başarısız"
export TR_INSTALL_WARN_EDGE="Kenar (edge) sürümü: %s dalı"
export TR_INSTALL_MSG_EDGE_HINT="Test sürümü; kararlı için: mo update"
export TR_INSTALL_ERR_HB_MANAGED="Homebrew Mole tam kurulum olmadan güncellenemez"
export TR_INSTALL_WARN_NOT_INST="Mole %s içinde yok; yeni kurulum."
export TR_INSTALL_ERR_LATEST_VER="Son Mole sürümü alınamadı."
export TR_INSTALL_HB_DETECTED="Mole Homebrew ile kurulu"
export TR_INSTALL_CHOOSE="Birini seçin:"
export TR_INSTALL_OPT_HB="1. Homebrew ile güncelle:"
export TR_INSTALL_OPT_MANUAL="2. Elle kuruluma geç:"
export TR_INSTALL_BUILDING_SRC="Kaynaktan derleniyor: %s"
export TR_INSTALL_DOWNLOADING="İndiriliyor: %s"
export TR_INSTALL_NOT_IN_PATH="%s PATH içinde değil"
export TR_INSTALL_PATH_HINT1="mole'u her yerden kullanmak için kabuk profilinize şunu ekleyin:"
export TR_INSTALL_PATH_HINT2="Örnek: ~/.zshrc veya ~/.bash_profile"
export TR_INSTALL_SUCCESS_FMT="Mole %s tamamlandı"
export TR_INSTALL_UPDATE_VIA_HB="Homebrew ile güncelleyin:"

# --------------------------------------------------------------------------
# lib/clean — tekrarlayan kalıplar
# --------------------------------------------------------------------------
export TR_CLEAN_WL_DRY_SKIP=" · önizleme, beyaz liste (atlanır)"
export TR_CLEAN_WL_SKIP=" · beyaz liste (atlandı)"
export TR_CLEAN_WL_DRY_CLEAN=" · önizleme, temizlenecek"
export TR_CLEAN_DOCKER_SKIP="Kullanılmayan Docker verisi · varsayılan atlandı"
export TR_CLEAN_DOCKER_REVIEW="İncele: docker system df"
export TR_CLEAN_DOCKER_PRUNE="Temizle: docker system prune --filter until=720h"

# --------------------------------------------------------------------------
# lib/uninstall/batch.sh, lib/ui/app_selector.sh
# --------------------------------------------------------------------------
export TR_BATCH_DECODE_FAIL="Dosya listesi çözülemedi: %s"
export TR_BATCH_NULL_BYTES="%s listesinde null bayt, reddedildi"
export TR_BATCH_INVALID_PATH="%s listesinde geçersiz yol: %s"
export TR_BATCH_NO_SELECTED="Kaldırma için uygulama seçilmedi"
export TR_BATCH_FILES_HEADER="Kaldırılacak dosyalar:"
export TR_BATCH_HB_ZAP="Homebrew uygulamaları tam temizlenir; --zap yapılandırma ve veriyi de kaldırır"
export TR_BATCH_CONFIRM_KEYS="Onay: Enter · İptal: ESC"
export TR_BATCH_ADMIN_DENIED="Yönetici erişimi reddedildi"
export TR_BATCH_REMOVING_FMT="%s kaldırılıyor (%s), bekleyin..."
export TR_BATCH_OK_INDEXED="[%d/%d] %s"
export TR_BATCH_OK_APP="%s"
export TR_BATCH_COULD_NOT_RM="Kaldırılamadı: %s"
export TR_BATCH_FAIL_FMT="%s başarısız: %s"
export TR_BATCH_FAIL_INDEXED="[%d/%d] %s"
export TR_APPSEL_NO_APPS="Kaldırılacak uygulama bulunamadı"
export TR_APPSEL_PREPARING="%d uygulama hazırlanıyor..."

# --------------------------------------------------------------------------
# Apple Silicon güncelleme bölümü
# --------------------------------------------------------------------------
export TR_AS_UPDATES="Apple Silicon Güncellemeleri"

# --------------------------------------------------------------------------
# bin/clean.sh — Ek Çeviriler
# --------------------------------------------------------------------------
export TR_BIN_CLEAN_USER_APP_CACHE="Kullanıcı uygulama önbelleği"
export TR_BIN_CLEAN_PROTECTED_FOUND="Korunan öğeler bulundu"
export TR_BIN_CLEAN_POTENTIAL_SPACE="Potansiyel alan: 0.00GB"
export TR_BIN_CLEAN_FREE_SPACE_LABEL="Boş alan:"
export TR_BIN_CLEAN_TEST_COMPLETE="Test modu tamamlandı"
export TR_BIN_CLEAN_TEST_NO_CLEANUP="Test modu - temizleme yapılmadı"
export TR_BIN_CLEAN_WL_CORE="çekirdek"
export TR_BIN_CLEAN_WL_PATTERNS_ACTIVE="desen etkin"
export TR_BIN_CLEAN_WL_LABEL="Beyaz liste:"
export TR_BIN_CLEAN_FDA_HINT="En iyi sonuç için Sistem Ayarları'ndan terminalinize Tam Disk Erişimi verin"
export TR_CLEAN_DRY_COMPLETE="Test tamamlandı - değişiklik yapılmadı"
export TR_CLEAN_POTENTIAL_SPACE="Potansiyel alan:"
export TR_CLEAN_ITEMS="Öğeler:"
export TR_CLEAN_CATEGORIES="Kategoriler:"
export TR_CLEAN_POTENTIAL_CLEANUP="Potansiyel temizleme:"
export TR_CLEAN_FILE_LIST="Ayrıntılı dosya listesi:"
export TR_CLEAN_WL_HINT="Koruma kuralları eklemek için mo clean --whitelist kullanın"
export TR_CLEAN_SPACE_FREED_LBL="Kazanılan alan:"
export TR_CLEAN_SPACE_FREED="Kazanılan alan"
export TR_CLEAN_ITEMS_CLEANED_LBL="Temizlenen öğe:"
# NOTE: aşağıdaki iki string'teki \$movies ifadesi call-site'ta bir değişken değildir,
# literal olarak görünür; ileride fix edilmesi gereken bir bug.
export TR_CLEAN_MOVIE_EQUIV_SINGLE="Yaklaşık ~\$movies adet 4K film alanına eşdeğer."
export TR_CLEAN_MOVIE_EQUIV_PLURAL="Yaklaşık ~\$movies adet 4K film alanına eşdeğer."
export TR_CLEAN_FREE_SPACE_NOW="Şu anki boş alan:"
export TR_CLEAN_ALREADY_CLEAN_DRY="Önemli geri kazanılabilir alan tespit edilmedi, sistem zaten temiz."
export TR_CLEAN_ALREADY_CLEAN="Sistem zaten temizdi; ek alan kazanılmadı."
export TR_BIN_CLEAN_MISSING_EXT_PATH="--external için yol eksik"
export TR_BIN_CLEAN_USE_DRY_RUN="Önizleme için --dry-run, korumak için --whitelist kullanın"
export TR_BIN_CLEAN_ADMIN_AVAIL="Yönetici erişimi var, sistem önizlemesi dahil"
export TR_BIN_CLEAN_SYSTEM_SUDO_DRY="Sistem önbellekleri sudo ister: sudo -v && mo clean --dry-run"
export TR_BIN_CLEAN_ADMIN_ALREADY="Yönetici erişimi zaten hazır"
export TR_BIN_CLEAN_SYS_SUDO_PROMPT="Sistem için sudo gerekir. Enter devam, Space atla: "
export TR_BIN_CLEAN_SKIPPED="Atlandı"
export TR_BIN_CLEAN_REQ_ADMIN="Sistem temizliği yönetici erişimi gerektirir"
export TR_BIN_CLEAN_ADMIN_GRANTED="Yönetici erişimi verildi"
export TR_BIN_CLEAN_AUTH_FAIL="Kimlik doğrulama başarısız"
export TR_BIN_CLEAN_CONT_USER="kullanıcı düzeyi temizlikle sürdürülüyor"
export TR_BIN_CLEAN_NON_INTERACTIVE="Etkileşimsiz modda çalışıyor"
export TR_BIN_CLEAN_SYS_ENABLED="Sistem düzeyi temizlik etkin, sudo oturumu açık"
export TR_BIN_CLEAN_SYS_SKIPPED="Sistem düzeyi atlandı, sudo gerekli"
export TR_BIN_CLEAN_USER_PROCEED="Kullanıcı düzeyi temizlik otomatik sürecek"
export TR_BIN_CLEAN_WL_CUSTOM="özel"
export TR_CLEAN_SCAN_ITEMS="Taranıyor %s öğe..."
export TR_CLEAN_SCAN_ITEMS_SHORT="Öğeler taranıyor..."

# --------------------------------------------------------------------------
# bin/uninstall.sh — Ek Çeviriler
# --------------------------------------------------------------------------
export TR_UNINSTALL_NO_APPS_MSG="Kaldırma için kullanılabilir uygulama yok"
export TR_UNINSTALL_NO_MATCH_FMT="Uyarı: '%s' ile eşleşen uygulama bulunamadı"
export TR_UNINSTALL_UNKNOWN_OPT="Bilinmeyen kaldırma seçeneği:"
export TR_UNINSTALL_WL_HINT="Beyaz liste yönetimi şu anda şunlar tarafından desteklenmektedir: mo clean --whitelist / mo optimize --whitelist"
export TR_UNINSTALL_HELP_HINT="Desteklenen seçenekler için 'mo uninstall --help' kullanın."
export TR_UNINSTALL_DRY_RUN_DETAIL="Uygulama dosyaları veya ayarları değiştirilmeyecek"
export TR_UNINSTALL_NO_MATCH_FOUND="Eşleşen uygulama bulunamadı."
export TR_UNINSTALL_MATCHED_APPS="%d uygulama eşleşti:"
export TR_UNINSTALL_LAST_LABEL="Son:"
export TR_UNINSTALL_CONFIRM_PROMPT="Kaldırma işlemine devam edilsin mi? [e/H] "
export TR_UNINSTALL_ABORTED="İptal edildi."
export TR_UNINSTALL_REFRESHING="Uygulama listesi yenileniyor..."
export TR_UNINSTALL_NO_SELECTED="Uygulama seçilmedi"
export TR_UNINSTALL_SELECTED_APPS="%d uygulama seçildi:"
export TR_UNINSTALL_RETURN_PROMPT="Uygulama listesine dönmek için Enter, çıkmak için q tuşuna basın (%d)"
export TR_UNINSTALL_LOG_WARN_FILE="Kaldırma için uygulama dosyası bulunamadı"
export TR_UNINSTALL_LOG_WARN_EMPTY="Kaldırılabilir uygulama yok"

# --------------------------------------------------------------------------
# bin/check.sh — Ek Çeviriler
# --------------------------------------------------------------------------
export TR_CHECK_TITLE="Sistem Kontrolü"
export TR_CHECK_RUNNING="Kontroller çalıştırılıyor..."

# --------------------------------------------------------------------------
# bin/analyze.sh & bin/status.sh — Ek Çeviriler
# --------------------------------------------------------------------------
export TR_ANALYZE_BIN_NOT_FOUND="Gömülü analiz dosyası bulunamadı. Mole'u yeniden yükleyin veya geri yüklemek için mo update çalıştırın."
export TR_STATUS_BIN_NOT_FOUND="Gömülü durum dosyası bulunamadı. Mole'u yeniden yükleyin veya geri yüklemek için mo update çalıştırın."

# --------------------------------------------------------------------------
# bin/completion.sh — Ek Çeviriler
# --------------------------------------------------------------------------
export TR_COMP_DRY_RUN_DETAIL="kabuk yapılandırma dosyaları değiştirilmeyecek"
export TR_COMP_NOT_IN_PATH="mole PATH'te bulunamadı, tamamlama etkinleştirmeden önce Mole'u yükleyin"
export TR_COMP_DRY_FISH="[TEST MODU] Fish tamamlamaları yazılacak:"
export TR_COMP_DRY_COMPLETE="Test tamamlandı, değişiklik yapılmadı"
export TR_COMP_FISH_TARGET="Fish tamamlamaları şuraya yazılacak:"
export TR_COMP_ENABLE_PROMPT="tamamlama etkinleştirilsin mi?"
export TR_COMP_ENABLE_HINT="Enter onayla / Q İptal"
export TR_COMP_CANCELLED="İptal edildi"
export TR_COMP_INVALID_KEY="Geçersiz tuş"
export TR_COMP_FISH_WRITTEN="Fish tamamlamaları yazıldı:"
export TR_COMP_UNSUPPORTED_SHELL="Desteklenmeyen kabuk:"
export TR_COMP_DRY_REMOVE_STALE="[TEST MODU] Eski tamamlama girdileri kaldırılacak..."
export TR_COMP_STALE_REMOVED="Eski tamamlama girdileri kaldırıldı:"
export TR_COMP_DRY_NORMALIZE="[TEST MODU] Tamamlama girdisi normalleştirilecek:"
export TR_COMP_UPDATED="Kabuk tamamlama güncellendi:"
export TR_COMP_WILL_ADD="Şuraya eklenecek:"
export TR_COMP_ADDED="Tamamlama eklendi:"
export TR_COMP_ACTIVATE_HINT="Şimdi etkinleştirmek için:"

# --------------------------------------------------------------------------
# lib/check/dev_environment.sh — Ek Çeviriler
# --------------------------------------------------------------------------
export TR_DEV_LA_HEALTHY="Başlatma aracıları tümü sağlıklı"
export TR_DEV_LA_BROKEN="bozuk"
export TR_DEV_TOOLS_NONE="Geliştirici araçları tespit edilmedi"
export TR_DEV_TOOLS_FOUND="bulundu"
export TR_DEV_VERSIONS_OK="Sürüm çakışması yok"
export TR_DEV_ENVIRONMENT="Geliştirici Ortamı"
export TR_DEV_VERSIONS_LABEL="Sürümler"
export TR_DEV_CONFLICT_PSQL_FMT="psql %s · sunucu %s"
export TR_DEV_CONFLICT_PY_FMT="python3 %s · pyenv %s"

# --------------------------------------------------------------------------
# lib/optimize/tasks.sh — Ek Çeviriler
# --------------------------------------------------------------------------
export TR_OPT_DNS_FAIL="DNS önbelleği yenilenemedi"
export TR_OPT_QUARANTINE_SKIP="Karantina temizleme atlandı, sqlite3 yok"
export TR_OPT_QUARANTINE_FAIL="Karantina veritabanı temizlenemedi"
export TR_OPT_DB_SKIP_SQLITE="Veritabanı zaten optimal, sqlite3 yok"
export TR_OPT_DB_CLOSE_APPS="Veritabanı optimizasyonu için bu uygulamaları kapatın:"
export TR_OPT_DB_INCOMPLETE="Veritabanı optimizasyonu tamamlanmadı"
export TR_OPT_LS_FAIL="LaunchServices yeniden oluşturulamadı"
export TR_OPT_LS_NOT_FOUND="lsregister bulunamadı"
export TR_OPT_FONT_SKIP_RUNNING="Font önbelleği yenileme atlandı · hâlâ çalışıyor"
export TR_OPT_FONT_FAIL="Font önbelleği temizlenemedi"
export TR_OPT_MEM_FAIL="Bellek baskısı serbest bırakılamadı"
export TR_OPT_NET_FAIL="Ağ yığını optimize edilemedi"
export TR_OPT_PERM_FAIL="İzinler onarılamadı, gerekli olmayabilir"
export TR_OPT_BT_DISCONNECT_NOTICE="Bluetooth cihazları yenileme sırasında kısa süreliğine bağlantısını kesebilir"
export TR_OPT_SPOTLIGHT_DISABLED="Spotlight dizinleme devre dışı"
export TR_OPT_SPOTLIGHT_OPTIMAL="Spotlight dizini zaten optimal"
export TR_OPT_SPOTLIGHT_SLOW="Spotlight araması yavaş, dizin yeniden oluşturuluyor, 1-2 saat sürebilir"
export TR_OPT_SPOTLIGHT_REBUILD_START="Spotlight dizini yeniden oluşturma başlatıldı"
export TR_OPT_SPOTLIGHT_BG="Dizinleme arka planda devam edecek"
export TR_OPT_SPOTLIGHT_FAIL="Spotlight dizini yeniden oluşturulamadı"
export TR_OPT_SPOTLIGHT_VERIFIED="Spotlight dizini doğrulandı"
export TR_OPT_DOCK_CLEARED="Dock önbelleği temizlendi"
export TR_OPT_DOCK_REFRESHED="Dock yenilendi"
export TR_OPT_DSSTORE_ALREADY=".DS_Store önleme zaten ağ ve USB birimlerinde etkin"
export TR_OPT_DSSTORE_ENABLED=".DS_Store önleme ağ ve USB birimlerinde etkinleştirildi"
export TR_OPT_LA_HEALTHY="Başlatma Aracıları tümü sağlıklı"
export TR_OPT_LA_CLEANED="%d bozuk başlatma aracı temizlendi"
export TR_OPT_PERIODIC_CURRENT="Periyodik bakım güncel"
export TR_OPT_PERIODIC_TRIGGERED="Periyodik bakım tetiklendi"
export TR_OPT_PERIODIC_FAIL="Periyodik bakım çalıştırılamadı"
export TR_OPT_SFL_NOT_FOUND="Paylaşılan dosya listeleri dizini bulunamadı"
export TR_OPT_SFL_REPAIRED="bozuk paylaşılan dosya listesi onarıldı"
export TR_OPT_SFL_HEALTHY="Paylaşılan dosya listeleri tümü sağlıklı"
export TR_OPT_NC_NOT_FOUND="Bildirim Merkezi veritabanı bulunamadı"
export TR_OPT_NC_HEALTHY="Bildirim Merkezi veritabanı sağlıklı"
export TR_OPT_NC_CLEANED="Bildirim Merkezi veritabanı temizlendi"
export TR_OPT_NC_SKIP="Bildirim Merkezi temizleme atlandı (veritabanı meşgul veya kilitli)"
export TR_OPT_SQLITE_UNAVAIL="sqlite3 mevcut değil"
export TR_OPT_DISK_VERIFY_DRY="Disk doğrulama · test modunda atlandı"
export TR_OPT_DISK_VERIFYING="Disk dosya sistemi doğrulanıyor..."
export TR_OPT_DISK_OK="Disk dosya sistemi doğrulandı"
export TR_OPT_DISK_ISSUES="Disk sorunları tespit edildi · çalıştırın: sudo diskutil repairVolume /"
export TR_OPT_DISK_COMPLETE="Disk doğrulama tamamlandı"
export TR_OPT_COREDUET_NOT_FOUND="Bilgi veritabanı bulunamadı"
export TR_OPT_COREDUET_HEALTHY="Bilgi veritabanı sağlıklı"
export TR_OPT_COREDUET_CLEANED="Bilgi veritabanı temizlendi"
export TR_OPT_COREDUET_SKIP="Bilgi veritabanı temizleme atlandı (veritabanı meşgul veya kilitli)"
export TR_OPT_LOGIN_SKIP_TEST="Giriş öğeleri denetimi · test modunda atlandı"
export TR_OPT_LOGIN_NONE="Giriş öğesi bulunamadı"
export TR_OPT_LOGIN_BROKEN="Bozuk giriş öğesi: %s (uygulama bulunamadı)"
export TR_OPT_LOGIN_HEALTHY_FMT="Tüm giriş öğeleri sağlıklı (%d denetlendi)"
export TR_OPT_LOGIN_BROKEN_HINT_FMT="%d bozuk giriş öğesi · Sistem Ayarları > Genel > Giriş Öğeleri"
export TR_OPT_UNKNOWN_ACTION="Bilinmeyen eylem:"
export TR_OPT_DRY_NO_FILES="Dosya değiştirilmez"
export TR_OPT_WOULD_DRY_BEFORE="Uygulanırdı"
export TR_OPT_WOULD_DRY_AFTER="optimizasyon uygulanırdı"
export TR_OPT_LINE_OPTIM_APPLIED="optimizasyon uygulandı"
export TR_OPT_ALL_TUNED="tüm hizmetler ayarlı"
export TR_OPT_SYS_HEALTH_FMT="Sistem  %.0f/%.0f GB Bellek | %.0f/%.0f GB Disk | Çalışma %.0fgün"
export TR_OPT_PROTECTED="Korundu"
export TR_OPT_SKIPPED="Atlandı"
export TR_OPT_FDA_HINT="Terminalinize Tam Disk Erişimi verip yeniden deneyin"
export TR_OPT_MISSING_BC="Eksik bağımlılık: bc"
export TR_OPT_INSTALL_BC="Kurulum: brew install bc"
export TR_OPT_HEALTH_FAIL="Sistem sağlık verisi alınamadı"
export TR_OPT_HEALTH_INVALID="Sistem sağlık verisi biçimi geçersiz"
export TR_OPT_CHECK_DEPS="awk, sysctl ve df komutlarının erişilebilir olduğunu denetleyin"
export TR_OPT_WL_ACTIVE="Etkin beyaz liste:"
export TR_OPT_ADMIN_REQ="Sistem optimizasyonu yönetici erişimi ister"
export TR_OPT_ENTRIES="kayıt"

# --------------------------------------------------------------------------
# lib/manage/update.sh — Ek Çeviriler
# --------------------------------------------------------------------------
export TR_UPD_UPDATES="güncelleme"
export TR_UPD_MOLE_PROMPT="Mole şimdi güncellensin mi?"
export TR_UPD_SKIP="atla"
export TR_UPD_YES="evet"
export TR_UPD_BREW_HINT="Güncellemek için brew upgrade çalıştırın"
export TR_UPD_MACOS_HINT="Sistem Ayarları → Genel → Yazılım Güncelleme açın"
export TR_UPD_APPSTORE_HINT="App Store → Güncellemeler açın"
export TR_UPD_UPDATING_MOLE="Mole güncelleniyor..."
export TR_UPD_MOLE_UPDATED="Mole güncellendi"
export TR_UPD_MOLE_FAIL="Mole güncellemesi başarısız"
export TR_UPD_MOLE_NOT_FOUND="Mole çalıştırılabilir dosyası bulunamadı"
export TR_UPD_NONE="Yapılacak güncelleme yok"
export TR_UPD_ALL_COMPLETE="Tüm güncellemeler tamamlandı"
export TR_UPD_FAIL="Güncelleme başarısız oldu"
export TR_UPD_HB_FAIL="Homebrew yükseltmesi başarısız"
export TR_UPD_BREW_LABEL_FMT="Homebrew, %s"

# --------------------------------------------------------------------------
# lib/manage/autofix.sh — Ek Çeviriler
# --------------------------------------------------------------------------
export TR_FIX_FW_SUGGEST="Daha iyi güvenlik için Güvenlik Duvarını etkinleştirin"
export TR_FIX_FV_SUGGEST="FileVault'u Etkinleştir"
export TR_FIX_FV_HINT="Sistem Ayarları → Gizlilik ve Güvenlik → FileVault"
export TR_FIX_TID_SUGGEST="Sudo için Touch ID'yi etkinleştir"
export TR_FIX_ROSETTA_SUGGEST="Intel uygulama desteği için Rosetta 2 yükle"
# NOTE: \${cache_gb} ve \${DISK_FREE_GB} literal olarak görünür (bug);
# çağrı yerinde değişken genişlemesi yapılmıyor.
export TR_FIX_CACHE_SUGGEST="Önbellekleri temizleyerek \${cache_gb}GB boşaltın"
export TR_FIX_CACHE_HINT="Çalıştırın: mo clean"
export TR_FIX_BREW_SUGGEST="Homebrew uyarılarını düzeltin"
export TR_FIX_BREW_HINT="Ayrıntılar için çalıştırın: brew doctor"
export TR_FIX_DISK_SUGGEST="Düşük disk alanı, \${DISK_FREE_GB}GB boş"
export TR_FIX_DISK_HINT="Büyük dosyaları bulmak için çalıştırın: mo analyze"
export TR_FIX_SUGGESTIONS="Öneriler"
export TR_FIX_ALL_GOOD="Her şey yolunda görünüyor"
export TR_FIX_AUTO_LABEL="[otomatik]"
export TR_FIX_PROMPT="Sorunlar otomatik düzeltilsin mi?"
export TR_FIX_PROMPT_HINT="Enter onayla / Space iptal"
export TR_FIX_ADMIN_REQUIRED="Sistem düzeltmeleri yönetici erişimi gerektirir"
export TR_FIX_ADMIN_SKIP="Otomatik düzeltmeler atlanıyor, yönetici kimliği gerekli"
export TR_FIX_FW_ENABLING="Güvenlik Duvarı etkinleştiriliyor..."
export TR_FIX_FW_ENABLED="Güvenlik Duvarı etkinleştirildi"
export TR_FIX_FW_FAIL="Güvenlik Duvarı etkinleştirilemedi"
export TR_FIX_TID_CONFIGURING="Sudo için Touch ID yapılandırılıyor..."
export TR_FIX_TID_CONFIGURED="Touch ID yapılandırıldı"
export TR_FIX_TID_FAIL="Touch ID yapılandırılamadı"
export TR_FIX_ROSETTA_INSTALLING="Rosetta 2 yükleniyor..."
export TR_FIX_ROSETTA_INSTALLED="Rosetta 2 yüklendi"
export TR_FIX_ROSETTA_FAIL="Rosetta 2 yüklenemedi"
export TR_FIX_SUMMARY_APPLIED="Otomatik düzeltmeler uygulandı:"
export TR_FIX_SUMMARY_SKIPPED="Otomatik düzeltmeler atlandı: Değişiklik gerekmedi"

# --------------------------------------------------------------------------
# lib/manage/whitelist.sh — Ek Çeviriler
# --------------------------------------------------------------------------
export TR_WL_OPT_TITLE="Beyaz Liste Yöneticisi, Atlanacak sistem kontrollerini seçin"
export TR_WL_CLEAN_TITLE="Beyaz Liste Yöneticisi, Korunacak önbellekleri seçin"
export TR_WL_UPDATED="Beyaz Liste Güncellendi"
export TR_WL_PROTECTED_MIXED="önceden tanımlı + özel desen korunuyor"
export TR_WL_PROTECTED="önbellek korunuyor"
export TR_WL_CONFIG_LABEL="Yapılandırma:"

# --------------------------------------------------------------------------
# lib/manage/purge_paths.sh — Ek Çeviriler
# --------------------------------------------------------------------------
export TR_PP_TITLE="Temizleme Yolları Yapılandırması"
export TR_PP_CURRENT_PATHS="Geçerli Tarama Yolları:"
export TR_PP_NOT_FOUND="bulunamadı"
export TR_PP_CUSTOM_CONFIG="özel yol ile yapılandırma kullanılıyor"
export TR_PP_DEFAULT_CONFIG="varsayılan yol kullanılıyor"
export TR_PP_DEFAULT_PATHS="Varsayılan Yollar:"
export TR_PP_CONFIG_FILE="Yapılandırma Dosyası:"
export TR_PP_OPENING_EDITOR="düzenleyicide açılıyor..."
export TR_PP_SAVE_HINT="Değişiklikleri uygulamak için kaydedin ve çıkın. Varsayılanları kullanmak için boş bırakın."
export TR_PP_CONFIG_UPDATED="Yapılandırma güncellendi"
export TR_PP_RUN_HINT="Yeni yollarla temizlemek için 'mo purge' çalıştırın"

# --------------------------------------------------------------------------
# lib/clean/*.sh — spinners / cümleler
# --------------------------------------------------------------------------
export TR_CLEAN_SPIN_DS_META="Finder meta verisi temizleniyor..."
export TR_CLEAN_SPIN_SCAN_APPS_INST="Kurulu uygulamalar taranıyor..."
export TR_CLEAN_SPIN_ORPHAN_RES="Yetim uygulama kaynakları taranıyor..."
export TR_CLEAN_SPIN_ORPHAN_SVC="Yetim sistem hizmetleri taranıyor..."
export TR_CLEAN_SPIN_CACHES="Önbellekler taranıyor..."
export TR_CLEAN_SPIN_MAIL_ATTACH="Eski Mail ekleri temizleniyor..."
export TR_CLEAN_SPIN_EXT_VOLS="%s harici birim taranıyor..."
export TR_CLEAN_SPIN_APP_CACHES="Uygulama önbellekleri taranıyor..."
export TR_CLEAN_SPIN_SANDBOX="Korumalı uygulama önbellekleri taranıyor..."
export TR_CLEAN_SPIN_GROUP_CONT="Grup Konteynerları taranıyor..."
export TR_CLEAN_SPIN_EXT_VOL_ONE="Harici birim taranıyor..."
export TR_CLEAN_SPIN_APP_SUPPORT="Application Support taranıyor..."
export TR_CLEAN_SPIN_APP_SUP_BULK_PROGRESS="Application Support taranıyor... %s/%s [%s, toplu temiz]"
export TR_CLEAN_SPIN_APP_SUP_ITEMS_PROGRESS="Application Support taranıyor... %s/%s [%s, %s öğe]"
export TR_CLEAN_SPIN_APP_SUP_GROUP_BULK="Application Support taranıyor... grup [%s, toplu temiz]"
export TR_CLEAN_SPIN_APP_SUP_GROUP_ITEMS="Application Support taranıyor... grup [%s, %s öğe]"
export TR_CLEAN_SPIN_REQ_PERM="İzinler isteniyor..."
export TR_CLEAN_SPIN_CLEANING_FMT="%s temizleniyor..."
export TR_CLEAN_SPIN_SYSTEM_CACHES="Sistem önbellekleri temizleniyor..."
export TR_CLEAN_SPIN_SYS_TEMP="Sistem geçici dosyaları temizleniyor..."
export TR_CLEAN_SPIN_SYS_CRASH="Sistem çökme raporları temizleniyor..."
export TR_CLEAN_SPIN_SYS_LOGS="Sistem günlükleri temizleniyor..."
export TR_CLEAN_SPIN_SYS_LOGS_3P="Üçüncü taraf sistem günlükleri temizleniyor..."
export TR_CLEAN_SPIN_SYS_LIB_UPDATES="Sistem kitaplığı güncellemeleri taranıyor..."
export TR_CLEAN_SPIN_MACOS_INST="macOS yükleyici dosyaları taranıyor..."
export TR_CLEAN_SPIN_CODE_SIG="Tarayıcı kod imza önb. taranıyor..."
export TR_CLEAN_SPIN_DIAG="Sistem tanılama günlükleri temizleniyor..."
export TR_CLEAN_SPIN_POWER="Güç günlükleri temizleniyor..."
export TR_CLEAN_SPIN_MEM_EXC="Bellek istisna raporları temizleniyor..."
export TR_CLEAN_SPIN_TM_CFG="Time Machine yapılandırması denetleniyor..."
export TR_CLEAN_SPIN_BACKUP_VOL="Yedek birimleri denetleniyor..."
export TR_CLEAN_SPIN_SCAN_BACKUP_VOL="Yedek birimleri taranıyor..."
export TR_CLEAN_SPIN_TM_STATUS="Time Machine durumu denetleniyor..."
export TR_CLEAN_SPIN_LOCAL_SNAP="Yerel anlık görüntüler denetleniyor..."
export TR_CLEAN_SPIN_NPM_PATH="npm önbellek yolu denetleniyor..."
export TR_CLEAN_SPIN_STORE_PATH="store yolu denetleniyor..."
export TR_CLEAN_SPIN_BUN_PATH="bun önbellek yolu denetleniyor..."
export TR_CLEAN_SPIN_BUN_CLEAN="bun önbelleği temizleniyor..."
export TR_CLEAN_SPIN_XCODE_RT_VOL="Xcode çalışma zamanı birimleri taranıyor..."
export TR_CLEAN_SPIN_UNAVAIL_SIM="Kullanılamayan simülatörler denetleniyor..."
export TR_CLEAN_SPIN_DESC_FMT="%s temizleniyor..."
export TR_CLEAN_APPS_SKIP_LIB_PERM="Atlandı: Kitaplık klasörlerine erişim yok"
export TR_CLEAN_APPS_FOUND_FMT="Bulundu: %s kurulu uygulama"
export TR_CLEAN_APPS_CLEANED_ORPHAN_FMT="%s yetim öğe temizlendi, yaklaşık %sMB"
export TR_CLEAN_APPS_FOUND_ORPH_SVC="%s yetim sistem hizmeti bulundu"
export TR_CLEAN_APPS_CLEANED_SVC_FMT="%s yetim hizmet temizlendi, yaklaşık %s"
export TR_CLEAN_APPS_DS_META_DRY_FMT="%s dosya, %s önizleme"
export TR_CLEAN_APPS_DS_META_OK_FMT="%s dosya, %s"
export TR_CLEAN_SYS_NO_INCOMPLETE_TM="Eksik Time Machine yedeği yok"
export TR_CLEAN_SYS_TM_ACTIVE_SKIP="Time Machine yedeklemesi sürüyor, atlandı"
export TR_CLEAN_SYS_TM_INCOMPLETE_DRY="Eksik yedek: %s, %s önizleme"
export TR_CLEAN_SYS_TMUTIL_SKIP="tmutil yok, atlandı: %s"
export TR_CLEAN_SYS_TM_INCOMPLETE_OK="Eksik yedek: %s, %s"
export TR_CLEAN_SYS_TM_DEL_FAIL="Silinemedi: %s · elle sudo deneyin"
export TR_CLEAN_SYS_TM_APFS_DRY="Eksik APFS yedek (%s): %s, %s önizleme"
export TR_CLEAN_SYS_TM_APFS_OK="Eksik APFS yedek (%s): %s, %s"
export TR_CLEAN_SYS_TM_BUNDLE_DEL_FAIL="Paketten silinemedi: %s"
export TR_CLEAN_SYS_TM_STATUS_UNK="Time Machine durumu okunamadı; anlık görüntü atlandı"
export TR_CLEAN_SYS_TM_ACTIVE_SNAP="Time Machine etkin; yerel anlık atlandı"
export TR_CLEAN_SYS_TM_SNAP_WL="Yerel TM anlık görüntüleri:"
export TR_CLEAN_SYS_TM_SNAP_REVIEW="İncele: tmutil listlocalsnapshots /"
export TR_CLEAN_SYS_CACHES="Sistem önbellekleri"
export TR_CLEAN_SYS_TEMP="Sistem geçici dosyaları"
export TR_CLEAN_SYS_CRASH="Sistem çökme raporları"
export TR_CLEAN_SYS_LOGS="Sistem günlükleri"
export TR_CLEAN_SYS_3P_LOGS="Üçüncü taraf sistem günlükleri"
export TR_CLEAN_SYS_LIB_UPD="Sistem kütüphane güncellemeleri"
export TR_CLEAN_SYS_CODE_SIGN="Tarayıcı kod imza önbellekleri"
export TR_CLEAN_SYS_DIAG_LOGS="Sistem tanılama günlükleri"
export TR_CLEAN_SYS_POWER_LOGS="Güç günlükleri"
export TR_CLEAN_SYS_MEM_REPORTS="Bellek istisna raporları"
export TR_CLEAN_SYS_MACOS_INST="macOS Kurulum Verileri"
export TR_CLEAN_SYS_ITEMS="öğe"
export TR_CLEAN_USER_TRASH_DRY="Çöp · boşaltılacak, %s öğe"
export TR_CLEAN_USER_TRASH_OK_EMPTY="Çöp · zaten boş"
export TR_CLEAN_USER_TRASH_OK="Çöp · boşaltıldı, %s öğe"
export TR_CLEAN_USER_TRASH_OK_MULTI="Çöp · boşaltıldı, %s öğe"
export TR_CLEAN_USER_SKIP_DL="Atlandı: aktif indirme: %s"
export TR_CLEAN_USER_MAIL_CLEAN_FMT="%s günlükten eski Mail eki temizlendi, yaklaşık %sMB"
export TR_CLEAN_USER_CHROME_RUN_SKIP="Chrome açık · eski sürüm temizliği atlandı"
export TR_CLEAN_USER_CHROME_SYMLINK_SKIP="Chrome Current bağlantısı bozuk · sürüm temizliği atlandı"
export TR_CLEAN_USER_CHROME_VER_DRY="Chrome eski sürümler, %s klasör, %s önizleme"
export TR_CLEAN_USER_CHROME_VER_OK="Chrome eski sürümler, %s klasör, %s"
export TR_CLEAN_USER_EDGE_RUN_SKIP="Edge açık · eski sürüm temizliği atlandı"
export TR_CLEAN_USER_EDGE_SYMLINK_SKIP="Edge Current bağlantısı bozuk · sürüm temizliği atlandı"
export TR_CLEAN_USER_EDGE_VER_DRY="Edge eski sürümler, %s klasör, %s önizleme"
export TR_CLEAN_USER_EDGE_VER_OK="Edge eski sürümler, %s klasör, %s"
export TR_CLEAN_USER_EDGE_UPDATER_RUN="Edge açık · güncelleyici temizliği atlandı"
export TR_CLEAN_USER_EDGE_UPD_DRY="Edge güncelleyici eski sürümler, %s klasör, %s önizleme"
export TR_CLEAN_USER_EDGE_UPD_OK="Edge güncelleyici eski sürümler, %s klasör, %s"
export TR_CLEAN_USER_BRAVE_RUN_SKIP="Brave açık · eski sürüm temizliği atlandı"
export TR_CLEAN_USER_BRAVE_SYMLINK_SKIP="Brave Current bağlantısı bozuk · sürüm temizliği atlandı"
export TR_CLEAN_USER_BRAVE_VER_DRY="Brave eski sürümler, %s klasör, %s önizleme"
export TR_CLEAN_USER_BRAVE_VER_OK="Brave eski sürümler, %s klasör, %s"
export TR_CLEAN_USER_EXT_VOL_SKIP="Harici birimler, %s ağ birimi atlandı"
export TR_CLEAN_USER_SBX_DRY="Korumalı uyg. önb., önizleme"
export TR_CLEAN_USER_SBX_DRY_SZ="Korumalı uyg. önb., %s önizleme"
export TR_CLEAN_USER_SBX_OK="Korumalı uyg. önb., temizlendi"
export TR_CLEAN_USER_SBX_OK_SZ="Korumalı uyg. önb., %s"
export TR_CLEAN_USER_GC_DRY="Grup Konteyner günlük/önb., önizleme"
export TR_CLEAN_USER_GC_DRY_SZ="Grup Konteyner günlük/önb., %s önizleme"
export TR_CLEAN_USER_GC_OK="Grup Konteyner günlük/önb., temizlendi"
export TR_CLEAN_USER_GC_OK_SZ="Grup Konteyner günlük/önb., %s"
export TR_CLEAN_USER_EXT_CLEAN_DRY="Harici birim temizliği, %s, %s önizleme"
export TR_CLEAN_USER_EXT_CLEAN_OK="Harici birim temizliği, %s, %s"
export TR_CLEAN_USER_FF_RUN_CACHE="Firefox açık · önbellek atlandı"
export TR_CLEAN_USER_FF_RUN_PROF="Firefox açık · profil önb. atlandı"
export TR_CLEAN_USER_SKIP_APP_SUPP="Atlandı: Application Support erişim izni yok"
export TR_CLEAN_USER_APP_SUPP_DRY_MIN="App Support günlük/önb., en az %s önizleme"
export TR_CLEAN_USER_APP_SUPP_DRY="App Support günlük/önb., %s önizleme"
export TR_CLEAN_USER_APP_SUPP_OK_MIN="App Support günlük/önb., en az %s"
export TR_CLEAN_USER_APP_SUPP_OK="App Support günlük/önb., %s"
export TR_CLEAN_USER_FW_DRY="Önbellekli aygıt bell., %s dosya, %s önizleme"
export TR_CLEAN_USER_FW_OK="Önbellekli aygıt bell., %s dosya, %s"
export TR_CLEAN_USER_IOS_BACKUP_WARN="iOS yedekleri: %s, Yol: %s"
export TR_CLEAN_USER_MAIL_DATA_WARN="Mail verisi: %s, Yol: %s"
export TR_CLEAN_USER_MAIL_DL_WARN="Mail indirilenler: %s, Yol: %s"
export TR_CLEAN_USER_MACOS_INST_WARN="macOS yükleyici: %s, Yol: %s"
export TR_CLEAN_USER_MACOS_UPD_WARN="macOS güncelleme önb.: %s, Yol: %s"
export TR_CLEAN_USER_DOCKER_HDR="Docker depolama:"
export TR_CLEAN_USER_DOCKER_LINE="%s: %s, Geri kazanılabilir: %s"
export TR_CLEAN_USER_DOCKER_HINT="Çalıştır: docker system df"
export TR_CLEAN_USER_NO_LARGE="Yaygın konumlarda büyük öğe yok"
export TR_CLEAN_DEV_FOUND_FMT="%s: %s bulundu%s"
export TR_CLEAN_DEV_XCODE_DOC_RUN="Xcode açık · dokümantasyon önb. atlandı"
export TR_CLEAN_DEV_XCODE_DOC_SUDO="Xcode dokümantasyon önb. atlandı (sudo reddi)"
export TR_CLEAN_DEV_XCODE_DOC_RM="Xcode dokümantasyon önb. · %s eski indeks kaldırıldı"
export TR_CLEAN_DEV_XCODE_DOC_SKIP_PROT="Xcode dokümantasyon önb. · %s korunan atlandı"
export TR_CLEAN_DEV_XCODE_DOC_NONE="Xcode dokümantasyon önb. · temizlenecek yok"
export TR_CLEAN_DEV_XCODE_DOC_NO_RM="Xcode dokümantasyon önb. · öğe kaldırılmadı"
export TR_CLEAN_DEV_STALE_VER_DRY="%s · %s eski sürüm kaldırılacak (%s), son %s tutulur"
export TR_CLEAN_DEV_STALE_VER_OK="%s · %s eski sürüm kaldırıldı, %s"
export TR_CLEAN_DEV_RT_SCAN="Xcode çalışma zamanı birimleri · %s girdi taranıyor"
export TR_CLEAN_DEV_RT_DRY="Xcode çalışma zamanı · %s kullanılmayan, %s kullanımda"
export TR_CLEAN_DEV_RT_TOTAL="Çalışma zamanı toplam: %s (kullanılmayan %s, kullanımda %s)"
export TR_CLEAN_DEV_RT_MORE="... ve %s ek çalışma zamanı girdisi"
export TR_CLEAN_DEV_RT_UNUSED="Kullanılmıyor"
export TR_CLEAN_DEV_RT_IN_USE="Kullanımda"
export TR_CLEAN_DEV_RT_CLEAN="Xcode çalışma zamanı birimleri · zaten temiz"
export TR_CLEAN_DEV_RT_SUDO_SKIP="Xcode çalışma zamanı · atlandı (sudo reddi)"
export TR_CLEAN_DEV_RT_RM_FMT="Xcode çalışma zamanı · %s kaldırıldı (%s), %s korunan atlandı"
export TR_CLEAN_DEV_RT_RM_FMT2="Xcode çalışma zamanı · %s kaldırıldı (%s)"
export TR_CLEAN_DEV_RT_PROT_NONE="Xcode çalışma zamanı · korunan atlandı, silinen yok"
export TR_CLEAN_DEV_SIMCTL_NA="Xcode kullanılamayan simülatörler · simctl yok"
export TR_CLEAN_DEV_SIM_DRY="Xcode kullanılamayan simülatörler · %s, %s"
export TR_CLEAN_DEV_SIM_CLEAN="Xcode kullanılamayan simülatörler · zaten temiz"
export TR_CLEAN_DEV_SIM_RM="Xcode kullanılamayan simülatörler · %s kaldırıldı, %s"
export TR_CLEAN_DEV_SIM_DONE="Xcode kullanılamayan simülatörler · temizlik bitti, %s"
export TR_CLEAN_DEV_SIM_PARTIAL="Xcode kullanılamayan simülatörler · kısmen %s/%s, %s"
export TR_CLEAN_DEV_SIM_FALLBACK="Xcode kullanılamayan simülatörler · %s kaldırıldı (yedek), %s"
export TR_CLEAN_DEV_SIM_FAIL="Xcode kullanılamayan simülatör temizliği başarısız%s"
export TR_CLEAN_DEV_BUN_NAME="bun önbelleği"
export TR_CLEAN_DEV_GO_CACHE="Go önbelleği"
export TR_CLEAN_DEV_GO_BUILD_CACHE="Go derleme önbelleği"
export TR_CLEAN_DEV_GO_MOD_CACHE="Go modül önbelleği"
export TR_CLEAN_DEV_MISE_CACHE="mise önbelleği"
export TR_CLEAN_DEV_NIX_GC="Nix çöp toplama"
export TR_CLEAN_HINTS_NO_CLUES="Yaygın Sistem Verisi ipucu bulunamadı"
export TR_CLEAN_BREW_AUTOREMOVE_NOTE="Homebrew autoremove (cleanup atlandı)..."
export TR_CLEAN_BREW_CLEANUP_NOTE="Homebrew cleanup ve autoremove..."
export TR_CLEAN_CACHES_BROWSER_SW="Tarayıcı Service Worker önbellekleri taranıyor..."
export TR_CLEAN_CACHES_PROJ_SEARCH="Proje önbellekleri aranıyor..."
export TR_CLEAN_BREW_WL_SKIP="Homebrew · beyaz liste (atlandı)"
export TR_CLEAN_BREW_DRY_CLEANUP="Homebrew · önizleme cleanup ve autoremove"
export TR_CLEAN_BREW_SKIP_RECENT="Homebrew · %s gün önce temizlendi, atlandı"
export TR_CLEAN_BREW_CACHE_SMALL="Homebrew cleanup · önbellek %sMB, atlandı"
export TR_CLEAN_BREW_CLEANUP_HDR="Homebrew cleanup"
export TR_CLEAN_BREW_CLEANUP_ITEMS="Homebrew cleanup, %s öğe"
export TR_CLEAN_BREW_CLEANUP_TO="Homebrew cleanup zaman aşımı · elle brew cleanup çalıştırın"
export TR_CLEAN_BREW_ORPHAN="Yetim bağımlılıklar kaldırıldı, %s paket"
export TR_CLEAN_BREW_AUTO_TO="Autoremove zaman aşımı · elle brew autoremove çalıştırın"
export TR_CLEAN_APP_XCODE_DD_RUN="Xcode açık · DerivedData atlandı"
export TR_CLEAN_APP_XCODE_PROJ_1="proje"
export TR_CLEAN_APP_XCODE_PROJ_N="projeler"
export TR_CLEAN_APP_XCODE_DD_DRY="Xcode DerivedData · %s %s, %s"
export TR_CLEAN_APP_XCODE_DD_OK="Xcode DerivedData · %s %s, %s"
export TR_CLEAN_APP_SIM_RUN="Simülatör açık · Simülatör önb./gecici/günlük atlandı"
export TR_CLEAN_APP_XCODE_SKIP_DD="Xcode açık · DerivedData/Arşiv/Dokümantasyon atlandı"
export TR_CLEAN_APP_SPOTIFY_PROT="Spotify önbelleği korundu · çevrimdışı müzik algılandı"
export TR_CLEAN_CACHES_FIRST_SETUP="İlk kurulum"
export TR_CLEAN_CACHES_TCC_BODY1="macOS Kitaplık klasörlerine erişim için izin isteyecek."
export TR_CLEAN_CACHES_TCC_BODY2="%s izin iletişim kutusu görebilirsiniz; hepsini onaylayın."
export TR_CLEAN_CACHES_PRESS_ENTER="Devam için Enter'a basın: "
export TR_CLEAN_CACHES_SW_SUCC_PROT="%s Service Worker, %sMB, %s korunan"
export TR_CLEAN_CACHES_SW_SUCC="%s Service Worker, %sMB"
export TR_CLEAN_CACHES_SW_DRY="%s Service Worker, %sMB önizleme, %s korunan"
export TR_CLEAN_CACHES_PY_DRY_SKIPPED="Python bytecode önb. · %s, %s klasör, %s önizleme, %s atlandı"
export TR_CLEAN_CACHES_PY_DRY="Python bytecode önb. · %s, %s klasör, %s önizleme"
export TR_CLEAN_CACHES_PY_OK_SKIPPED="Python bytecode önb. · %s, %s klasör, %s, %s atlandı"
export TR_CLEAN_CACHES_PY_OK="Python bytecode önb. · %s, %s klasör, %s"
export TR_CLEAN_MAVEN_LOCAL_REPO="Maven yerel deposu"

# --------------------------------------------------------------------------
# Rapor sonrası ekler / Post-audit additions
# --------------------------------------------------------------------------
export TR_NA="Geçerli değil"
export TR_ERR_TEMP_FILE="Hata: Geçici dosya oluşturulamadı:"

export TR_RISK_SYS_ADMIN="Sistem dosyaları veya yönetici izni gerektirir"
export TR_RISK_PREFS="Uygulama ayarlarını etkileyebilecek tercih dosyaları"
export TR_RISK_INSTALLERS="Yükleyici paketleri veya uygulama verisi"
export TR_RISK_BACKUPS="Yedekleme veya indirilen dosyalar"
export TR_RISK_CACHES="Önbellek/log dosyaları, otomatik yeniden oluşturulur"
export TR_RISK_USER_DATA="Kullanıcı veri dosyaları"

export TR_HINT_XCODE_DD="Xcode DerivedData"
export TR_HINT_XCODE_ARCH="Xcode Arşivleri"
export TR_HINT_IPHONE_BACKUPS="iPhone yedekleri"
export TR_HINT_SIM_DATA="Simülatör verisi"
export TR_HINT_DOCKER_DATA="Docker Desktop verisi"
export TR_HINT_MAIL_DATA="Mail verisi"
export TR_HINT_CANDIDATES="aday"
export TR_HINT_AT_LEAST="en az"
export TR_HINT_SAMPLED_FROM="şundan örnek:"
export TR_HINT_SAMPLED="örneklenmiş"
export TR_HINT_ITEMS="öğe"
export TR_HINT_EXAMPLES="Örnekler:"
export TR_HINT_MISSING_APP="Eksik uygulama/hedef"
export TR_HINT_APP_NOT_FOUND="İlişkili uygulama yok"
export TR_HINT_STALE_LOGIN="Olası eski giriş öğesi:"
export TR_HINT_LA_REVIEW="İncele: ~/Library/LaunchAgents — yalnızca tanıdıklarınızı kaldırın"
export TR_HINT_PATH="Yol"
export TR_HINT_REVIEW="İncele"

# --------------------------------------------------------------------------
# Harici birim yol doğrulama
# --------------------------------------------------------------------------
export TR_USER_EXT_VOL_MISSING="Harici birim yolu eksik"
export TR_USER_EXT_VOL_NOT_ABS="Harici birim yolu mutlak olmalı: %s"
export TR_USER_EXT_VOL_NOT_EXISTS="Harici birim yolu yok: %s"
export TR_USER_EXT_VOL_UNDER_ROOT="Yol %s altında olmalı: %s"
export TR_USER_EXT_VOL_SYMLINK="Bağlantılı birim yolu reddedildi: %s"
export TR_USER_EXT_VOL_ONLY_SUPPORTS="Yalnızca %s altındaki bağlı yollar: %s"

# --------------------------------------------------------------------------
# lib/manage/whitelist.sh — önbellek ve optimize beyaz liste satır etiketleri
# --------------------------------------------------------------------------
export TR_WL_CACHE_001="Apple Mail önbelleği"
export TR_WL_CACHE_002="Gradle derleme önbelleği (Android Studio, Gradle)"
export TR_WL_CACHE_003="Gradle arka plan süreç önbelleği"
export TR_WL_CACHE_004="Xcode DerivedData (çıktı, dizinler)"
export TR_WL_CACHE_005="Xcode arşivleri (paketlenmiş uygulamalar)"
export TR_WL_CACHE_006="Xcode dahili önbellek dosyaları"
export TR_WL_CACHE_007="Xcode iOS cihaz destek sembolleri"
export TR_WL_CACHE_008="Maven yerel deposu (Java bağımlılıkları)"
export TR_WL_CACHE_009="JetBrains IDE verisi (IntelliJ, PyCharm, WebStorm, GoLand)"
export TR_WL_CACHE_010="JetBrains IDE önbelleği"
export TR_WL_CACHE_011="Android Studio önbelleği ve dizinleri"
export TR_WL_CACHE_012="Android derleme önbelleği"
export TR_WL_CACHE_013="VS Code çalışma zamanı önbelleği"
export TR_WL_CACHE_014="VS Code uzantı ve güncelleme önbelleği"
export TR_WL_CACHE_015="VS Code sistem önbelleği (Cursor, VSCodium)"
export TR_WL_CACHE_016="Cursor düzenleyici önbelleği"
export TR_WL_CACHE_017="Bazel derleme önbelleği"
export TR_WL_CACHE_018="Go derleme önbelleği"
export TR_WL_CACHE_019="Go modül önbelleği"
export TR_WL_CACHE_020="Rust Cargo kayıt önbelleği"
export TR_WL_CACHE_021="Rust belgelendirme önbelleği"
export TR_WL_CACHE_022="Rustup araç zinciri indirmeleri"
export TR_WL_CACHE_023="ccache derleyici önbelleği"
export TR_WL_CACHE_024="sccache dağıtık derleyici önbelleği"
export TR_WL_CACHE_025="SBT Scala derleme önbelleği"
export TR_WL_CACHE_026="Ivy bağımlılık önbelleği"
export TR_WL_CACHE_027="Turbo monorepo derleme önbelleği"
export TR_WL_CACHE_028="Next.js derleme önbelleği"
export TR_WL_CACHE_029="Vite derleme önbelleği"
export TR_WL_CACHE_030="Parcel paketleyici önbelleği"
export TR_WL_CACHE_031="pre-commit kancaları önbelleği"
export TR_WL_CACHE_032="Ruff Python linter önbelleği"
export TR_WL_CACHE_033="MyPy tip denetleyici önbelleği"
export TR_WL_CACHE_034="Pytest test önbelleği"
export TR_WL_CACHE_035="Flutter SDK önbelleği"
export TR_WL_CACHE_036="Swift Package Manager önbelleği"
export TR_WL_CACHE_037="Zig derleyici önbelleği"
export TR_WL_CACHE_038="Deno önbelleği"
export TR_WL_CACHE_039="CocoaPods önbelleği (iOS bağımlılıkları)"
export TR_WL_CACHE_040="npm paket önbelleği"
export TR_WL_CACHE_041="pip Python paket önbelleği"
export TR_WL_CACHE_042="uv Python paket önbelleği"
export TR_WL_CACHE_043="R renv genel önbelleği (sanal ortamlar)"
export TR_WL_CACHE_044="tealdeer tldr sayfa önbelleği"
export TR_WL_CACHE_045="Homebrew indirilen paketler"
export TR_WL_CACHE_046="Yarn paket yöneticisi önbelleği"
export TR_WL_CACHE_047="pnpm paket deposu"
export TR_WL_CACHE_048="Composer PHP bağımlılık önbelleği (eski)"
export TR_WL_CACHE_049="Composer PHP bağımlılık önbelleği"
export TR_WL_CACHE_050="RubyGems önbelleği"
export TR_WL_CACHE_051="Conda paket önbelleği"
export TR_WL_CACHE_052="Anaconda paket önbelleği"
export TR_WL_CACHE_053="PyTorch model önbelleği"
export TR_WL_CACHE_054="TensorFlow model ve veri kümesi önbelleği"
export TR_WL_CACHE_055="HuggingFace modelleri ve veri kümeleri"
export TR_WL_CACHE_056="Playwright tarayıcı ikilileri"
export TR_WL_CACHE_057="Selenium WebDriver ikilileri"
export TR_WL_CACHE_058="Ollama yerel yapay zeka modelleri"
export TR_WL_CACHE_059="W&B ML deney önbelleği"
export TR_WL_CACHE_060="Safari web tarayıcı önbelleği"
export TR_WL_CACHE_061="Chrome tarayıcı önbelleği"
export TR_WL_CACHE_062="Firefox tarayıcı önbelleği"
export TR_WL_CACHE_063="Brave tarayıcı önbelleği"
export TR_WL_CACHE_064="Surge vekil önbelleği"
export TR_WL_CACHE_065="Surge yapılandırma ve verisi"
export TR_WL_CACHE_066="Docker BuildX önbelleği"
export TR_WL_CACHE_067="Podman konteyner önbelleği"
export TR_WL_CACHE_068="Font önbelleği"
export TR_WL_CACHE_069="Spotlight üstveri önbelleği"
export TR_WL_CACHE_070="CloudKit önbelleği"
export TR_WL_CACHE_071="Çöp Kutusu"
export TR_WL_CACHE_072="iOS/iPadOS aygıt bell. (.ipsw) iTunes/Finder"
export TR_WL_CACHE_073="Apple Configurator 2 aygıt bell. (.ipsw)"
export TR_WL_CACHE_FINDER_META="Finder üstverisi, .DS_Store"
export TR_WL_OPT_01="macOS Güvenlik Duvarı denetimi"
export TR_WL_OPT_02="Gatekeeper denetimi"
export TR_WL_OPT_03="macOS sistem güncellemeleri denetimi"
export TR_WL_OPT_04="Mole güncelleme denetimi"
export TR_WL_OPT_05="Homebrew sağlık denetimi (doctor)"
export TR_WL_OPT_06="SIP durum denetimi"
export TR_WL_OPT_07="FileVault durum denetimi"
export TR_WL_OPT_08="TouchID sudo denetimi"
export TR_WL_OPT_09="Rosetta 2 denetimi"
export TR_WL_OPT_10="Git yapılandırma denetimi"
export TR_WL_OPT_11="Giriş öğeleri denetimi"

fi
